stages:
  - prepare
  - test
  - doc
  - pypi

variables:
  ARTIFACTORY_GROUPS: "readers,deployers"
  ARTIFACTORY_TOKEN_VARS: "ARTIFACTORY_API_KEY,TWINE_PASSWORD"
  ARTIFACTORY_USERNAME_VARS: "ARTIFACTORY_USERNAME,TWINE_USERNAME"

include:
  - project: 'devops/artifactory-token-helper'
    file: '/.gitlab-ci-artifactory-token.yml'

cache:
  paths:
    - windows/

.pytest:
  script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - python -m pytest

python-3.8:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/python-3.8:latest
  before_script:
    - python -V

macos:
  extends: .pytest
  stage: test
  tags:
    - os-macos
  before_script:
    - python3 -V
    - rm -rf venv
    - pip3 install virtualenv
    - virtualenv venv -p python3
    - source venv/bin/activate
    - pip install --upgrade pip

windows:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/windows-python-3.8:latest
  tags:
    - docker-windows
  before_script:
    - python -V

docs:
  extends: .pytest
  stage: test
  image: docker.audeering.com/audeering/python-3.8:latest
  script:
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - python -m sphinx -W docs/ -d build/doctrees build/html -b html
    - python -m sphinx -W docs/ build/linkcheck -b linkcheck
  artifacts:
    paths:
      - build/

pages:
  stage: doc
  image: docker.audeering.com/alpine
  variables:
    GIT_STRATEGY: none  # disable git fetch
  script:
    - cp -r build/html public
  dependencies:
    - docs
  artifacts:
    paths:
      - public
  only:
    refs:
      - tags

pypi:
  extends: .pytest
  stage: pypi
  image: docker.audeering.com/audeering/python-3.8:latest
  script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload --repository local dist/*
  only:
    refs:
      - tags
